### ISSUE TITLE
Not able to flash UF2 Bootloader 

### ISSUE THREAD

**Issue by bogdanbrudiu** [makerdiary/nrf52840-mdk-usb-dongle#42]
I have the dongle connected in DFU mode (the red led is blinking), I am able to read the device using nrf connect.
When using the urfutil I get this error:

```
PS C:\Users\carmi\Downloads\opensk> ./nrfutil dfu usb-serial -pkg uf2_bootloader-0.2.13-44-gb2b4284-nosd_signed.zip -p COM3

Traceback (most recent call last):
  File "nordicsemi\__main__.py", line 1537, in <module>
  File "site-packages\click\core.py", line 764, in __call__
  File "site-packages\click\core.py", line 717, in main
  File "site-packages\click\core.py", line 1137, in invoke
  File "site-packages\click\core.py", line 1137, in invoke
  File "site-packages\click\core.py", line 956, in invoke
  File "site-packages\click\core.py", line 555, in invoke
  File "nordicsemi\__main__.py", line 1015, in usb_serial
  File "nordicsemi\__main__.py", line 970, in do_serial
  File "nordicsemi\dfu\dfu.py", line 123, in dfu_send_images
  File "nordicsemi\dfu\dfu.py", line 95, in _dfu_send_image
  File "nordicsemi\dfu\dfu_transport_serial.py", line 256, in send_init_packet
  File "nordicsemi\dfu\dfu_transport_serial.py", line 421, in __execute
  File "nordicsemi\dfu\dfu_transport_serial.py", line 505, in __get_response
pc_ble_driver_py.exceptions.NordicSemiException: Response Code InvalidObject
[11292] Failed to execute script __main__
PS C:\Users\carmi\Downloads\opensk>
```

Any idea what i'm doing wrong...

**Comment by caizelin** [comment]
@bogdanbrudiu If you are in UF2 Bootloader mode, use `adafruit-nrfutil` instead of `nrfutil`.
